if (NOT (JAVA_HOME AND IS_DIRECTORY "${JAVA_HOME}"))
  find_program(JAVA_EXE java)
  if (NOT JAVA_EXE OR NOT EXISTS "${JAVA_EXE}")
    message(FATAL_ERROR "No java executable")
  endif ()
  get_filename_component(JAVA_EXE_ROOT ${JAVA_EXE} REALPATH)
  get_filename_component(JAVA_EXE_DIR ${JAVA_EXE_ROOT} DIRECTORY)
  get_filename_component(JAVA_HOME ${JAVA_EXE_DIR}/../../ ABSOLUTE)
  message(STATUS JAVA_HOME=${JAVA_HOME})
endif ()
