/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kz_pompei_vipro_core_mediator_RenderCore */

#ifndef _Included_kz_pompei_vipro_core_mediator_RenderCore
#define _Included_kz_pompei_vipro_core_mediator_RenderCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kz_pompei_vipro_core_mediator_RenderCore
 * Method:    init0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kz_pompei_vipro_core_mediator_RenderCore_init0
  (JNIEnv *, jclass);

/*
 * Class:     kz_pompei_vipro_core_mediator_RenderCore
 * Method:    initReference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kz_pompei_vipro_core_mediator_RenderCore_initReference
  (JNIEnv *, jobject);

/*
 * Class:     kz_pompei_vipro_core_mediator_RenderCore
 * Method:    destroyReference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kz_pompei_vipro_core_mediator_RenderCore_destroyReference
  (JNIEnv *, jobject);

/*
 * Class:     kz_pompei_vipro_core_mediator_RenderCore
 * Method:    getSize
 * Signature: ()Lkz/pompei/vipro/core/mediator/Size;
 */
JNIEXPORT jobject JNICALL Java_kz_pompei_vipro_core_mediator_RenderCore_getSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
